version: '3'

services:
  todo-app:
    build: ./
    command: ./todo-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_PASSWORD: "postgres"

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

volumes:
  db-data: