name: Go

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Init mod
      run: go mod init github.com/edamiyan/todo-app
      
    - name: Install all requirements
      run: go mod tidy -v
    
    - name: Build
      run: go build -v ./cmd/main.go
